# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87397c69d1d642be36f14683cac743a984c3a041f52132c018203ddc2b6bc7f8c5fb9ea8be559281ad64088503c85ca36d6f6c452f7fcba120b676dcf8325da2

test:
  secret_key_base: 444986a3baa6e69cf7946566700d3e8f4c11040e2d217e74e2e9e5302324bf809f03121d598ae27daa2fa98e742a3120907060ff79ac81a8b83ad7067fb9eff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
